/**
 * 표기통일 잡음 필터 회귀 코퍼스 (KEEP = 유지, DROP = 제외).
 *
 * 새 휴리스틱·수확 꼬리를 넣을 때 이 목록을 먼저 돌린다.
 * - KEEP 깨짐 → 캐나다⊃나다 등 명사복합 오탐
 * - DROP 깨짐 → 잡음이 다시 목록에 섞임
 * - 조사 가드(`붉`≠`붉+은`)는 LeftHeuristic 단위 테스트로 별도 고정
 *
 * @typedef {{ spaced: string, note?: string }} UnifyNoiseCorpusCase
 */

/** @type {readonly UnifyNoiseCorpusCase[]} */
export const UNIFY_NOISE_REGRESSION_KEEP = Object.freeze([
  { spaced: '캐나다 정부', note: '체언 내부 …나다 ≠ 용언 어미' },
  { spaced: '경리 업무', note: '명사+명사 유지' },
  { spaced: '주식 시장', note: '명사+명사 유지' },
  { spaced: '미국 정부', note: '명사+명사 유지' },
  { spaced: '미국 최고', note: '명사+명사 유지' },
  { spaced: '직장 사람', note: '명사+명사(@사람) 유지' },
  { spaced: '가게 주인', note: '명사 가게 — -게 제외' },
  { spaced: '집게 도구', note: '명사 집게 — -게 제외' },
  { spaced: '목적 의식', note: '명사 목적 ≠ 관형 -적' },
  { spaced: '목적의식', note: '명사 목적(붙임) ≠ 맨꼬리 적' },
  { spaced: '실적 관리', note: '명사 실적 ≠ 관형 -적' },
  { spaced: '실적관리', note: '명사 실적(붙임)' },
  { spaced: '보고서작성', note: '붙임 infix가 고서 substring 오탐 안 함' },
]);

/** @type {readonly UnifyNoiseCorpusCase[]} */
export const UNIFY_NOISE_REGRESSION_DROP = Object.freeze([
  { spaced: '대부분 공무원', note: '예외 어절(왼쪽)' },
  { spaced: '대부분의 사람', note: '예외 어절+의' },
  { spaced: '가족 모두', note: '예외 어절(오른쪽)' },
  { spaced: '가족 끼리', note: '의존명사' },
  { spaced: '결혼 직전', note: '시점 의존명사' },
  { spaced: '가정하고 공무원', note: '용언 연결' },
  { spaced: '가치있다고 시장', note: '수확 꼬리' },
  { spaced: '구성되며 시장', note: '수확 꼬리' },
  { spaced: '기록하여 결과', note: '하다 활용' },
  { spaced: '결혼 하고자', note: '명사+하다' },
  { spaced: '결혼 하려고', note: '명사+하다' },
  { spaced: '결혼 하였고', note: '명사+하다' },
  { spaced: '결혼 했어', note: '명사+하다' },
  { spaced: '내가 공무원', note: '짧은 체언+격조사' },
  { spaced: '등이 공무원', note: '등+이' },
  { spaced: '들어서 공무원', note: '용언 연결 어서' },
  { spaced: '보면 공무원', note: '본보조 보면' },
  // 관형형 어미 닫힌집합 — 명사 아님
  { spaced: '아는 사람', note: '관형형 -는' },
  { spaced: '못하는 사람', note: '관형형 -는' },
  { spaced: '사는 사람', note: '관형형 -는' },
  { spaced: '말하는 사람', note: '관형형 -는' },
  { spaced: '않는 사람', note: '관형형 -는' },
  { spaced: '않은 사람', note: '관형형 -은' },
  { spaced: '높은 사람', note: '관형형 -은' },
  { spaced: '붉은 표시', note: '관형형 -은 (명사 아님)' },
  // 세션 잡음 (의존명사·조사·담화·용언 조각)
  { spaced: '거품 때문', note: '의존명사 때문' },
  { spaced: '경기후퇴 때문', note: '의존명사 때문' },
  { spaced: '가치 마저', note: '조사 마저' },
  { spaced: '않고 시장', note: '용언 조각 않고' },
  { spaced: '아니냐며 정책', note: '담화 어절 아니냐며' },
  { spaced: '어떤 정책', note: '관형사 어떤' },
  { spaced: '신속히 자금', note: '부사 -히' },
  { spaced: '통해 자금', note: '매개 통해' },
  { spaced: '팔아 자금', note: '용언 연결 팔아' },
  { spaced: '만약 대출', note: '담화 만약' },
  { spaced: '의심스러운 대출', note: '스럽다 관형 꼬리 스러운' },
  { spaced: '의심스러운대출', note: '스럽다 관형 꼬리 스러운(붙임)' },
  { spaced: '과열된 시장', note: '관형형 -된' },
  { spaced: '당시 시장', note: '시점 어절 당시' },
  { spaced: '약탈적 시장', note: '관형 접미 닫힌 약탈적' },
  { spaced: '약탈적시장', note: '관형 접미 닫힌 약탈적(붙임)' },
  { spaced: '이르러 시장', note: '용언 연결 이르러' },
  { spaced: '내놓고 자금', note: '용언 연결 내놓고' },
  { spaced: '모든 자금', note: '관형사 모든' },
  { spaced: '여전히 자금', note: '부사 여전히' },
  { spaced: '그리고 대출', note: '접속 그리고' },
  { spaced: '다른 대출', note: '관형사 다른' },
  { spaced: '꾸준히 성장', note: '부사 -히' },
  { spaced: '엄청난 성장', note: '관형 형용사 엄청난' },
  { spaced: '언제 성장', note: '의문 부사 언제' },
  { spaced: '인해 성장', note: '매개 인해' },
  { spaced: '잠재웠기 시장', note: '용언 명사화 잠재웠기' },
  { spaced: '그런데 시장', note: '접속 닫힌 Set' },
  { spaced: '그러나 정책', note: '접속 닫힌 Set 역접' },
  { spaced: '따라서 시장', note: '접속 닫힌 Set 인과' },
  { spaced: '또한 공무원', note: '접속 닫힌 Set 나열' },
  { spaced: '다시 시장', note: '부사 다시' },
  { spaced: '동안 시장', note: '의존명사 동안' },
  { spaced: '일단 시장', note: '부사 일단' },
  { spaced: '금융 관련', note: '의존·수식 관련(좌우)' },
  { spaced: '관련 금융', note: '관련 오른쪽·왼쪽 동일' },
  { spaced: '아니라 공무원', note: '이다 부정 연결 아니라' },
  { spaced: '공무원 아니라', note: '아니라 오른쪽' },
  { spaced: '야기시킨 공무원', note: '사동 관형 시킨' },
  { spaced: '게도 주택', note: '의존명사 게+도' },
  { spaced: '품고 공무원', note: '용언 연결 품고' },
  { spaced: '가정이건', note: '이다 연결 이건' },
  { spaced: '가정 이건', note: '이다 연결 이건(띄움)' },
  { spaced: '과외 받아', note: '보조·본용언 받아' },
  { spaced: '과외받아', note: '보조·본용언 받아(붙임)' },
  { spaced: '과외시키', note: '사동 시키' },
  { spaced: '과외 시키', note: '사동 시키(띄움)' },
  { spaced: '경제 따위', note: '의존명사 따위' },
  { spaced: '경제따위', note: '의존명사 따위(붙임)' },
  { spaced: '계산 되거', note: '줄바꿈 잘림 되거나' },
  { spaced: '계산되거', note: '줄바꿈 잘림 되거나(붙임)' },
  { spaced: '계산 하거', note: '줄바꿈 잘림 하거나' },
  { spaced: '계산하거', note: '줄바꿈 잘림 하거나(붙임)' },
  { spaced: '게재하였음', note: '하다 과거 종결 하였음' },
  { spaced: '게재 하였음', note: '하다 과거 종결 하였음(띄움)' },
  { spaced: '넘어 박물관', note: '용언 연결 넘어' },
  { spaced: '넘어박물관', note: '용언 연결 넘어(붙임)' },
  { spaced: '따라 박물관', note: '접속 따라' },
  { spaced: '따라박물관', note: '접속 따라(붙임)' },
  { spaced: '따른 박물관', note: '관형형 따른' },
  { spaced: '따른박물관', note: '관형형 따른(붙임)' },
  { spaced: '공무원 만드', note: '줄바꿈 잘림 만들다' },
  { spaced: '공무원만드', note: '줄바꿈 잘림 만들다(붙임)' },
  { spaced: '각각 주택', note: '배분 관형·부사 각각' },
  { spaced: '각각주택', note: '배분 관형·부사 각각(붙임)' },
  { spaced: '세계 곳곳', note: '부사 곳곳' },
  { spaced: '세계곳곳', note: '부사 곳곳(붙임)' },
  { spaced: '구성 되므', note: '줄바꿈 잘림 되므로' },
  { spaced: '구성되므', note: '줄바꿈 잘림 되므로(붙임)' },
  { spaced: '그냥 시장', note: '부사 그냥' },
  { spaced: '그냥시장', note: '부사 그냥(붙임)' },
  { spaced: '깨달았듯 시장', note: '의존 듯 연결' },
  { spaced: '깨달았듯시장', note: '의존 듯 연결(붙임)' },
  { spaced: '떨어뜨리고 시장', note: '용언 연결 떨어뜨리고' },
  { spaced: '떨어뜨리고시장', note: '용언 연결 떨어뜨리고(붙임)' },
  { spaced: '말해 시장', note: '용언 연결 말해' },
  { spaced: '말해시장', note: '용언 연결 말해(붙임)' },
  { spaced: '앞서 시장', note: '부사·매개 앞서' },
  { spaced: '앞서시장', note: '부사·매개 앞서(붙임)' },
  { spaced: '위해 시장', note: '목적 매개 위해' },
  { spaced: '위해시장', note: '목적 매개 위해(붙임)' },
  { spaced: '이때 시장', note: '시점 어절 이때' },
  { spaced: '이때시장', note: '시점 어절 이때(붙임)' },
  { spaced: '주로 시장', note: '부사 주로' },
  { spaced: '주로시장', note: '부사 주로(붙임)' },
  { spaced: '강한 기업', note: '하다 관형 꼬리 강한' },
  { spaced: '강한기업', note: '하다 관형 꼬리 강한(붙임)' },
  { spaced: '몇몇 기업', note: '수량 관형 몇몇' },
  { spaced: '몇몇기업', note: '수량 관형 몇몇(붙임)' },
  { spaced: '물론 기업', note: '담화 부사 물론' },
  { spaced: '물론기업', note: '담화 부사 물론(붙임)' },
  { spaced: '속한 기업', note: '하다 관형 꼬리 속한' },
  { spaced: '속한기업', note: '하다 관형 꼬리 속한(붙임)' },
  { spaced: '지닌 기업', note: '관형형 지닌' },
  { spaced: '지닌기업', note: '관형형 지닌(붙임)' },
  { spaced: '해당 기업', note: '한정 관형 해당' },
  { spaced: '해당기업', note: '한정 관형 해당(붙임)' },
  { spaced: '경우 기업', note: '상황 명사 경우' },
  { spaced: '경우기업', note: '상황 명사 경우(붙임)' },
  { spaced: '그저 기업', note: '부사 그저' },
  { spaced: '그저기업', note: '부사 그저(붙임)' },
  { spaced: '이로써 시장', note: '접속 부사 이로써' },
  { spaced: '이로써시장', note: '접속 부사 이로써(붙임)' },
  { spaced: '사실상 시장', note: '부사 사실상' },
  { spaced: '사실상시장', note: '부사 사실상(붙임)' },
  { spaced: '특정 시장', note: '한정 관형 특정' },
  { spaced: '특정시장', note: '한정 관형 특정(붙임)' },
  { spaced: '없으며 공무원', note: '용언 연결 없으며' },
  { spaced: '이런 공무원', note: '관형사 이런' },
  { spaced: '공무원 이런', note: '이런 오른쪽' },
  { spaced: '해서 공무원', note: '하다 연결 해서' },
  { spaced: '했더니 공무원', note: '하다 연결 했더니' },
  { spaced: '되면 주택', note: '되다 연결 되면' },
  { spaced: '끝에 공무원', note: '1음절+에 (Kiwi NNG+JKB)' },
  { spaced: '앞에 주택', note: '1음절+에' },
  { spaced: '뒤에 시장', note: '1음절+에' },
  { spaced: '곳에서 공무원', note: '1음절+에서' },
  { spaced: '금융에 시장', note: '2음절+에 (Kiwi NNG+JKB)' },
  { spaced: '시장 금융에', note: '금융에 오른쪽' },
  { spaced: '캐나다에 정부', note: '3음절+에 — 명사+조사' },
  // 세션 추가 (용언 연결·부사·조사 이든)
  { spaced: '빌려 자금', note: '용언 연결 빌려' },
  { spaced: '터라 자금', note: '용언·종결 조각 터라' },
  { spaced: '쉽게 대출', note: '부사 -게' },
  { spaced: '빠르게 성장', note: '부사 -게' },
  { spaced: '기업 이든', note: '조사·접속 이든 (휴리스틱)' },
]);

/**
 * 리스트 휴리스틱 밖(가지+ㄴ·만하+ㄴ) — Kiwi 2차 POS로만 DROP.
 * @type {readonly UnifyNoiseCorpusCase[]}
 */
export const UNIFY_NOISE_REGRESSION_DROP_KIWI_ADNOMINAL = Object.freeze([
  { spaced: '가진 사람', note: '관형형 종성ㄴ(가진) — Kiwi POS' },
  { spaced: '만한 사람', note: '관형형 종성ㄴ(만한) — Kiwi POS' },
]);

/** 붙임·단독 표면 (띄움 쌍이 아닌 DROP) */
/** @type {readonly { surface: string, note?: string }[]} */
export const UNIFY_NOISE_REGRESSION_DROP_SURFACES = Object.freeze([
  { surface: '담당하던', note: '하던 꼬리' },
  { surface: '광고니까', note: '이다 연결' },
  { surface: '결혼하고자', note: '하고자' },
  { surface: '가족끼리', note: '예외 접미' },
  { surface: '결혼직전', note: '예외 접미' },
  { surface: '가치마저', note: '명사+조사 마저' },
  { surface: '신뢰해선', note: '하다 활용 해선' },
  { surface: '잠재웠기', note: '용언 명사화 잠재웠기' },
  { surface: '야기시킨', note: '사동 관형 시킨' },
]);
